language: node_js
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - "node"
script:
  - travis_wait 30 npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    target_branch: master
    on:
      branch: src
