language: node_js
sudo: false
dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
node_js:
  - "node"
script:
  - npm run build
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: dist
    target_branch: gh-pages
    on:
      branch: master
